services:
  - type: web
    name: innovatex-portal
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/public
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
